//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epam.FixAntenna.NetCore.Validation.Error.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epam.FixAntenna.NetCore.Validation.Error.Resource.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - value is incorrect (out of range). [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE__OUT_OF_RANGE_FOR_TAG {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE__OUT_OF_RANGE_FOR_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - incorrect data type. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_INCORRECT_DATA_TYPE {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_INCORRECT_DATA_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - incorrect NumInGroup count for repeating group. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_INCORRECT_NUMINGROUP_COUNT {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_INCORRECT_NUMINGROUP_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - Invalid message type. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_INVALID_MESSAGE_TYPE {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_INVALID_MESSAGE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - invalid tag number. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_INVALID_TAG_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_INVALID_TAG_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - missing value. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_MISSING_VALUE {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_MISSING_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - required tag missing. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_REQUIRED_TAG_MISSING {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_REQUIRED_TAG_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - tag appears more then once. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_TAG_APPEARS_MORE_THEN_ONCE {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_TAG_APPEARS_MORE_THEN_ONCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - tag in group is out of order. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_TAG_IN_GROUP_IS_OUT_OF_ORDER {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_TAG_IN_GROUP_IS_OUT_OF_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - tag is out of order. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_TAG_IS_OUT_OF_ORDER {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_TAG_IS_OUT_OF_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - tag is outside of repeating group. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_TAG_IS_OUTSIDE_REPEATING_GROUP {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_TAG_IS_OUTSIDE_REPEATING_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - tag is repeated incorrect number of time(s). [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_TAG_IS_REPEATED_INCORRECT_NUMBER_TIME {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_TAG_IS_REPEATED_INCORRECT_NUMBER_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - tag not defined. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_TAG_NOT_DEFINED {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_TAG_NOT_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - tag not defined for the repeating group. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_TAG_NOT_DEFINED_REPEATING_GROUP {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_TAG_NOT_DEFINED_REPEATING_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - undefined tag. [SeqNum: {0}, MsgType: {1}, Tag: {2}].
        /// </summary>
        internal static string INVALID_MESSAGE_UNDEFINED_TAG {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_UNDEFINED_TAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message - unsupported MsgType. [SeqNum: {0}, MsgType: {1}, Tag: N/A].
        /// </summary>
        internal static string INVALID_MESSAGE_UNSUPPORTED_MSGTYPE {
            get {
                return ResourceManager.GetString("INVALID_MESSAGE_UNSUPPORTED_MSGTYPE", resourceCulture);
            }
        }
    }
}
