//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epam.FixAntenna.AdminTool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Epam.FixAntenna.AdminTool.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is incorrect because the XML request is invalid..
        /// </summary>
        internal static string InvalidXmlData {
            get {
                return ResourceManager.GetString("InvalidXmlData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute `{0}` command: {1}..
        /// </summary>
        internal static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot only for SessionsList completed..
        /// </summary>
        internal static string OperationSessionListSnapshotSuccess {
            get {
                return ResourceManager.GetString("OperationSessionListSnapshotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe only for SessionsList completed..
        /// </summary>
        internal static string OperationSessionListSubscribeSuccess {
            get {
                return ResourceManager.GetString("OperationSessionListSubscribeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe for SessionsList completed..
        /// </summary>
        internal static string OperationSessionListUnsubscribeSnapshotSuccess {
            get {
                return ResourceManager.GetString("OperationSessionListUnsubscribeSnapshotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe with snapshot for SessionsList completed..
        /// </summary>
        internal static string OperationSessionListWithSnapshotSuccess {
            get {
                return ResourceManager.GetString("OperationSessionListWithSnapshotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} completed..
        /// </summary>
        internal static string OperationSuccess {
            get {
                return ResourceManager.GetString("OperationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute `{0}` command: Unknown session sender:{1}, target:{2}..
        /// </summary>
        internal static string OperationUnknownSenderTarget {
            get {
                return ResourceManager.GetString("OperationUnknownSenderTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute `{0}` command: Unknown session: {1}..
        /// </summary>
        internal static string OperationUnknownSessionId {
            get {
                return ResourceManager.GetString("OperationUnknownSessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message is incorrect because it contains duplicate RequestID..
        /// </summary>
        internal static string RequestIdHasBeenUsed {
            get {
                return ResourceManager.GetString("RequestIdHasBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdminTool is unable to process non FIX XML message..
        /// </summary>
        internal static string UnableToProcessNotXmldata {
            get {
                return ResourceManager.GetString("UnableToProcessNotXmldata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlData is empty..
        /// </summary>
        internal static string XmlDataIsEmpty {
            get {
                return ResourceManager.GetString("XmlDataIsEmpty", resourceCulture);
            }
        }
    }
}
